name: MonitorAPI
version: '${project.version}'
main: me.caps123987.monitorapi.MonitorAPI
api-version: '1.21.4'
authors: [CAPS123987]
##commands:
##  dtest:
##    description: Test command
##    usage: /dtest

folia-supported: true
depend:
  - packetevents