name: Build MonitorAPI JAR
 on: 
   push:
 permissions:
   actions: read
   contents: write
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-java@v4
         with:
           java-version: '21'
           distribution: 'temurin'
       - run: mvn clean package
       - uses: softprops/action-gh-release@v2
         with:
           tag_name: 1.${{github.run_number}}-Beta
           files: target/MonitorAPI.jar
   release:
     if: github.ref == 'refs/heads/releases'
     needs: [build]
     runs-on: ubuntu-latest
     steps:
       - uses: softprops/action-gh-release@v2
         with:
           tag_name: 1.${{github.run_number}}-Beta
           files: target/MonitorAPI.jar
